### ISSUE TITLE
pak install error 

### ISSUE THREAD

**Issue by derekibw** [embedthis/kickstart#1]
[Warn] Cannot get remote versions for: https://github.com/embedthis/esp-angular-gui
pak: ERROR: Command failed, status 128
remote: Repository not found.
fatal: repository 'https://github.com/embedthis/esp-angular-gui/' not found

**Comment by dev-embedthis** [comment]
What command did you type?

**Comment by derekibw** [comment]
Find the esp-angular-gui in the previous version by tag, copy the file to the paks directory, and then execute the pak install successfully.

**Comment by dev-embedthis** [comment]
Thanks for the details. We'll test it out.
